apiVersion: batch/v1
kind: Job
metadata:
  name: general-diner-job
  labels:
    kueue.x-k8s.io/queue-name: "general-entrance-lq"
spec:
  parallelism: 3
  completions: 3
  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
        args: ["300s"]
        resources:
          requests:
            cpu: 1
      restartPolicy: Never
