apiVersion: batch/v1
kind: Job
metadata:
  name: vip-job
  labels:
    kueue.x-k8s.io/queue-name: "vip-entrance-lq"
spec:
  parallelism: 5
  completions: 5
  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
        args: ["300s"]
        resources:
          requests:
            cpu: 1
      restartPolicy: Never
