apiVersion: batch/v1
kind: Job
metadata:
  name: late-arrival-job
  labels:
    kueue.x-k8s.io/queue-name: "late-arrival-lq"
spec:
  parallelism: 4 
  completions: 4
  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
        args: ["120s"]
        resources:
          requests: { cpu: 1 }
      restartPolicy: Never

